apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: rostam63/multi-client
      context: client # directory (folder)
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': . # when scaffold sees a js file changes, throw that to the container
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
